name: flutter_assignment_lovoj
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  connectivity_plus: ^4.0.1
  intl: any
  shared_preferences: ^2.0.17
  get_it: ^7.2.01
  flutter_bloc: ^8.1.2
  dio: ^5.3.2
  equatable: ^2.0.5
  fluttertoast: ^8.2.1
  gson: ^0.1.4
  flutter_svg: ^2.0.2
  auto_size_text: ^3.0.0
  pinput: ^3.0.0
  country_code_picker: ^3.0.0
  freezed: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
